In [61]:
%load_ext autoreload

import pandas as pd

df = pd.read_csv(
    "data/unpacked/data-2/export_request_20240508/thintergen_share_geno_VM2_1_FinalReport.txt",
    sep="\t",
    header=9,
)

df

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

,SNP Name,Sample ID,Allele1 - AB,Allele2 - AB,Chr,Position
0,ARS-BFGL-NGS-104320,HORUS007200114646,A,B,0,0
1,ARS-BFGL-NGS-55064,HORUS007200114646,A,B,0,0
2,UA-IFASA-9429,HORUS007200114646,B,A,0,0
3,BTA-67276-no-rs,HORUS007200114646,A,A,0,0
4,BTA-89233-no-rs,HORUS007200114646,B,B,0,0
...,...,...,...,...,...,...
1085207,AX-28607688,HORUS003910309577,-,-,31,8939596
1085208,BovineHD3100001376,HORUS003910309577,-,-,31,9388211
1085209,BovineHD3100000364,HORUS003910309577,-,-,31,12978879
1085210,AX-28607817,HORUS003910309577,-,-,31,42192549
1085211,BovineHD3100001409,HORUS003910309577,-,-,31,42639036

In [62]:
df = df.iloc[:]
df

,SNP Name,Sample ID,Allele1 - AB,Allele2 - AB,Chr,Position
0,ARS-BFGL-NGS-104320,HORUS007200114646,A,B,0,0
1,ARS-BFGL-NGS-55064,HORUS007200114646,A,B,0,0
2,UA-IFASA-9429,HORUS007200114646,B,A,0,0
3,BTA-67276-no-rs,HORUS007200114646,A,A,0,0
4,BTA-89233-no-rs,HORUS007200114646,B,B,0,0
...,...,...,...,...,...,...
1085207,AX-28607688,HORUS003910309577,-,-,31,8939596
1085208,BovineHD3100001376,HORUS003910309577,-,-,31,9388211
1085209,BovineHD3100000364,HORUS003910309577,-,-,31,12978879
1085210,AX-28607817,HORUS003910309577,-,-,31,42192549
1085211,BovineHD3100001409,HORUS003910309577,-,-,31,42639036

In [63]:
df

,SNP Name,Sample ID,Allele1 - AB,Allele2 - AB,Chr,Position
0,ARS-BFGL-NGS-104320,HORUS007200114646,A,B,0,0
1,ARS-BFGL-NGS-55064,HORUS007200114646,A,B,0,0
2,UA-IFASA-9429,HORUS007200114646,B,A,0,0
3,BTA-67276-no-rs,HORUS007200114646,A,A,0,0
4,BTA-89233-no-rs,HORUS007200114646,B,B,0,0
...,...,...,...,...,...,...
1085207,AX-28607688,HORUS003910309577,-,-,31,8939596
1085208,BovineHD3100001376,HORUS003910309577,-,-,31,9388211
1085209,BovineHD3100000364,HORUS003910309577,-,-,31,12978879
1085210,AX-28607817,HORUS003910309577,-,-,31,42192549
1085211,BovineHD3100001409,HORUS003910309577,-,-,31,42639036

In [64]:
snp_map_df = pd.read_csv(
    "data/unpacked/data-2/export_request_20240508/thintergen_share_geno_VM2_1_SNPMap.txt",
    sep="\t",
)

snp_map_df

,Index,Name,Chromosome,Position,GenTrain Score,SNP,ILMN_Strand,Customer Strand,NormID
0,NaN,ARS-BFGL-NGS-104320,0,0,NaN,NaN,NaN,NaN,NaN
1,NaN,ARS-BFGL-NGS-55064,0,0,NaN,NaN,NaN,NaN,NaN
2,NaN,UA-IFASA-9429,0,0,NaN,NaN,NaN,NaN,NaN
3,NaN,BTA-67276-no-rs,0,0,NaN,NaN,NaN,NaN,NaN
4,NaN,BTA-89233-no-rs,0,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
63831,NaN,AX-28607688,31,8939596,NaN,NaN,NaN,NaN,NaN
63832,NaN,BovineHD3100001376,31,9388211,NaN,NaN,NaN,NaN,NaN
63833,NaN,BovineHD3100000364,31,12978879,NaN,NaN,NaN,NaN,NaN
63834,NaN,AX-28607817,31,42192549,NaN,NaN,NaN,NaN,NaN
63835,NaN,BovineHD3100001409,31,42639036,NaN,NaN,NaN,NaN,NaN

In [65]:
bovinehd_manifest_df = pd.read_csv(
    "data/manifest/BovineHD_B1.csv", sep=",", header=7, skipfooter=24
)
pd.set_option("display.max_columns", None)

/tmp/ipykernel_1343336/306765753.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  bovinehd_manifest_df = pd.read_csv(

In [66]:
display(bovinehd_manifest_df[bovinehd_manifest_df["Name"] == "Hapmap43437-BTA-101873"])

,IlmnID,Name,IlmnStrand,SNP,AddressA_ID,AlleleA_ProbeSeq,AddressB_ID,AlleleB_ProbeSeq,GenomeBuild,Chr,MapInfo,Ploidy,Species,Source,SourceVersion,SourceStrand,SourceSeq,TopGenomicSeq,BeadSetID,Exp_Clusters,Intensity_Only,RefStrand
771336,Hapmap43437-BTA-101873-0_B_R_1511566689,Hapmap43437-BTA-101873,BOT,[T/C],45674375,GACCACATGCAGCCTGTTTTCCCAGGTGACTGAACATGAAATAAGG...,NaN,NaN,UMD_3.1,1,135098,diploid,Bos taurus,UM3,0,TOP,CAACAAATGTTGGAGAACCACTGGTCTAGGGAATCTTTAAACCCTA...,CAACAAATGTTGGAGAACCACTGGTCTAGGGAATCTTTAAACCCTA...,260,3,0,-

In [67]:
def create_TopGenomicSeq(row):
    first = row["TopGenomicSeq"].split("/")[0][-1]
    second = row["TopGenomicSeq"].split("/")[1][0]
    return f"[{first}/{second}]"


def create_SourceSeq_SNP(row):
    first = row["SourceSeq"].split("/")[0][-1]
    second = row["SourceSeq"].split("/")[1][0]
    return f"[{first}/{second}]"


bovinehd_manifest_df["TopGenomicSeq_SNP"] = bovinehd_manifest_df.apply(
    create_TopGenomicSeq, axis=1
)

bovinehd_manifest_df["SourceSeq_SNP"] = bovinehd_manifest_df.apply(
    create_SourceSeq_SNP, axis=1
)

display(bovinehd_manifest_df[bovinehd_manifest_df["Name"] == "ARS-BFGL-NGS-65067"])

,IlmnID,Name,IlmnStrand,SNP,AddressA_ID,AlleleA_ProbeSeq,AddressB_ID,AlleleB_ProbeSeq,GenomeBuild,Chr,MapInfo,Ploidy,Species,Source,SourceVersion,SourceStrand,SourceSeq,TopGenomicSeq,BeadSetID,Exp_Clusters,Intensity_Only,RefStrand,TopGenomicSeq_SNP,SourceSeq_SNP
19067,ARS-BFGL-NGS-65067-0_T_R_1511651937,ARS-BFGL-NGS-65067,TOP,[A/G],42619401,TGTGCTATAAATAGCAAGCGGATTAAAGCTAATCTAGAGGGCCAGC...,NaN,NaN,UMD_3.1,1,883895,diploid,Bos taurus,UM3,0,BOT,CTGCCTTTTTTTTTTCCTTCTCTTTCTGGCTTCCATTTGCTTCAGT...,GTTTACAGAGTGTGCTATAAATAGCAAGCGGATTAAAGCTAATCTA...,282,3,0,-,[A/G],[T/C]

In [68]:
bovinehd_manifest_df = bovinehd_manifest_df[
    [
        "Name",
        "IlmnStrand",
        "SNP",
        "MapInfo",
        "Chr",
        "SourceSeq_SNP",
        "SourceSeq",
        "TopGenomicSeq_SNP",
        "TopGenomicSeq",
        "SourceStrand",
        "RefStrand",
    ]
]

rdf = pd.merge(df, bovinehd_manifest_df, left_on="SNP Name", right_on="Name")
rdf.drop(columns=["Name"], inplace=True)

rdf

,SNP Name,Sample ID,Allele1 - AB,Allele2 - AB,Chr_x,Position,IlmnStrand,SNP,MapInfo,Chr_y,SourceSeq_SNP,SourceSeq,TopGenomicSeq_SNP,TopGenomicSeq,SourceStrand,RefStrand
0,ARS-BFGL-NGS-104320,HORUS007200114646,A,B,0,0,TOP,[A/G],11696849,3,[T/C],TGGCGTGCTGCAATTCATGGGGTCGCAAAGAGTCAGACACGACTGA...,[A/G],TTTATAAATAAATTTATGGATAAACAAAATCAGGTAGGGCCATAAA...,BOT,+
1,ARS-BFGL-NGS-55064,HORUS007200114646,A,B,0,0,BOT,[T/C],57139923,22,[A/G],GGGTTCGAGCGCCTCAACCGCAGACCTGCCTGCCTCAACCAAGGCC...,[A/G],GGGTTCGAGCGCCTCAACCGCAGACCTGCCTGCCTCAACCAAGGCC...,TOP,+
2,BTA-89233-no-rs,HORUS007200114646,B,B,0,0,BOT,[T/C],31819343,23,[T/C],TATAATACATATAATATTGTTTACAATATTCTGTTGCTTTATTATG...,[A/G],TTAAAATTAATAAAATAAGATCAAGAAAAAATTATCAATATAAGAA...,BOT,-
3,ARS-BFGL-NGS-116515,HORUS007200114646,B,A,0,0,TOP,[A/C],4644991,28,[T/G],ATGGGGTCATACAGAGTTGGACACGACTGAAGCGACTTAGCAGCAG...,[A/C],CAACTGAGTGACTGAACTGAAGAATATGTAAATAATTATCGGCCTG...,BOT,-
4,UA-IFASA-7534,HORUS007200114646,B,B,0,0,TOP,[A/G],41108931,29,[A/G],GAAGGCTAGCTGACATCAGCCACACAGGAGCTCTTCCTCTCAAGTG...,[A/G],GAAGGCTAGCTGACATCAGCCACACAGGAGCTCTTCCTCTCAAGTG...,TOP,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022222,BovineHD3100001188,HORUS003910309577,-,-,31,7385231,TOP,[A/C],50965063,17,[A/C],GGAGTATAAGTCCATTTCACTTTTCTTTGGGTACTCGTTCCATCAC...,[A/C],GGAGTATAAGTCCATTTCACTTTTCTTTGGGTACTCGTTCCATCAC...,TOP,+
1022223,BovineHD3100001052,HORUS003910309577,-,-,31,8919894,TOP,[A/C],0,0,[A/C],AAGGGTTTATTTTTATTGTATGCCAAAAACTACATCCTTTGCAGTG...,[A/C],AAGGGTTTATTTTTATTGTATGCCAAAAACTACATCCTTTGCAGTG...,TOP,+
1022224,BovineHD3100001376,HORUS003910309577,-,-,31,9388211,BOT,[T/C],7293970,29,[T/C],AGAAACACATGTGGTGAAGGGGTCTGGAGGTGGGCCCTGTAGTGAC...,[A/G],GGCTCCACAGACAGCTTGCATGTACCTGAGTCATCCCCATTTGGGA...,BOT,-
1022225,BovineHD3100000364,HORUS003910309577,-,-,31,12978879,BOT,[T/G],0,0,[A/C],AAATCATATAGAAATAGATCTCAGAATTTAAAAAAAAAAAATTGCT...,[A/C],AAATCATATAGAAATAGATCTCAGAATTTAAAAAAAAAAAATTGCT...,TOP,+
1022226,BovineHD3100001409,HORUS003910309577,-,-,31,42639036,BOT,[T/G],0,0,[A/C],ACAGTGACATATTTGAAGATGTCAGAAGCAATGGGCTAGATTGATT...,[A/C],ACAGTGACATATTTGAAGATGTCAGAAGCAATGGGCTAGATTGATT...,TOP,+

In [69]:
import importlib

import tools

importlib.reload(tools)


def create_column_REF(coord_key):
    if coord_key[0] == "0" or coord_key[0] == 0:
        return None
    return tools.get_ref_base(coord_key[0], coord_key[1])


rdf["coord_key"] = list(zip(rdf["Chr_x"], rdf["Position"]))


rdf["REF"] = rdf["coord_key"].map(create_column_REF)

rdf.drop(columns=["coord_key"], inplace=True)


display(rdf)

,SNP Name,Sample ID,Allele1 - AB,Allele2 - AB,Chr_x,Position,IlmnStrand,SNP,MapInfo,Chr_y,SourceSeq_SNP,SourceSeq,TopGenomicSeq_SNP,TopGenomicSeq,SourceStrand,RefStrand,REF
0,ARS-BFGL-NGS-104320,HORUS007200114646,A,B,0,0,TOP,[A/G],11696849,3,[T/C],TGGCGTGCTGCAATTCATGGGGTCGCAAAGAGTCAGACACGACTGA...,[A/G],TTTATAAATAAATTTATGGATAAACAAAATCAGGTAGGGCCATAAA...,BOT,+,None
1,ARS-BFGL-NGS-55064,HORUS007200114646,A,B,0,0,BOT,[T/C],57139923,22,[A/G],GGGTTCGAGCGCCTCAACCGCAGACCTGCCTGCCTCAACCAAGGCC...,[A/G],GGGTTCGAGCGCCTCAACCGCAGACCTGCCTGCCTCAACCAAGGCC...,TOP,+,None
2,BTA-89233-no-rs,HORUS007200114646,B,B,0,0,BOT,[T/C],31819343,23,[T/C],TATAATACATATAATATTGTTTACAATATTCTGTTGCTTTATTATG...,[A/G],TTAAAATTAATAAAATAAGATCAAGAAAAAATTATCAATATAAGAA...,BOT,-,None
3,ARS-BFGL-NGS-116515,HORUS007200114646,B,A,0,0,TOP,[A/C],4644991,28,[T/G],ATGGGGTCATACAGAGTTGGACACGACTGAAGCGACTTAGCAGCAG...,[A/C],CAACTGAGTGACTGAACTGAAGAATATGTAAATAATTATCGGCCTG...,BOT,-,None
4,UA-IFASA-7534,HORUS007200114646,B,B,0,0,TOP,[A/G],41108931,29,[A/G],GAAGGCTAGCTGACATCAGCCACACAGGAGCTCTTCCTCTCAAGTG...,[A/G],GAAGGCTAGCTGACATCAGCCACACAGGAGCTCTTCCTCTCAAGTG...,TOP,-,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022222,BovineHD3100001188,HORUS003910309577,-,-,31,7385231,TOP,[A/C],50965063,17,[A/C],GGAGTATAAGTCCATTTCACTTTTCTTTGGGTACTCGTTCCATCAC...,[A/C],GGAGTATAAGTCCATTTCACTTTTCTTTGGGTACTCGTTCCATCAC...,TOP,+,T
1022223,BovineHD3100001052,HORUS003910309577,-,-,31,8919894,TOP,[A/C],0,0,[A/C],AAGGGTTTATTTTTATTGTATGCCAAAAACTACATCCTTTGCAGTG...,[A/C],AAGGGTTTATTTTTATTGTATGCCAAAAACTACATCCTTTGCAGTG...,TOP,+,T
1022224,BovineHD3100001376,HORUS003910309577,-,-,31,9388211,BOT,[T/C],7293970,29,[T/C],AGAAACACATGTGGTGAAGGGGTCTGGAGGTGGGCCCTGTAGTGAC...,[A/G],GGCTCCACAGACAGCTTGCATGTACCTGAGTCATCCCCATTTGGGA...,BOT,-,G
1022225,BovineHD3100000364,HORUS003910309577,-,-,31,12978879,BOT,[T/G],0,0,[A/C],AAATCATATAGAAATAGATCTCAGAATTTAAAAAAAAAAAATTGCT...,[A/C],AAATCATATAGAAATAGATCTCAGAATTTAAAAAAAAAAAATTGCT...,TOP,+,T
1022226,BovineHD3100001409,HORUS003910309577,-,-,31,42639036,BOT,[T/G],0,0,[A/C],ACAGTGACATATTTGAAGATGTCAGAAGCAATGGGCTAGATTGATT...,[A/C],ACAGTGACATATTTGAAGATGTCAGAAGCAATGGGCTAGATTGATT...,TOP,+,G

In [70]:
# def get_alt_from_normalized(row):
#     ref_allele = row["REF"]
#     # normalized_alleles = row['Normalized_SNP']
#     TopGenomicSeq_SNP = row["TopGenomicSeq_SNP"].strip("[]").split("/")
#     SourceSeq_SNP = row["SourceSeq_SNP"].strip("[]").split("/")
#     TopGenomicSeq_Left = row["TopGenomicSeq"].split("[")[0][-20:].upper()
#     SourceSeq_Left = row["SourceSeq"].split("[")[0][-20:].upper()


#     if int(row["MapInfo"]) == 0 or int(row["MapInfo"]) == 0:
#         return "DATA_ERROR"
#     base = tools.get_ref_base(
#         int(row["Chr_y"]), int(row["MapInfo"] - 1), int(row["MapInfo"] - 20)
#     )

#     if len(TopGenomicSeq_Left) != len(base) or len(SourceSeq_Left) != len(base):
#         print("base", len(base))
#         print("TopGenomicSeq_Left", len(TopGenomicSeq_Left))
#         print("SourceSeq_SNP_Left", len(SourceSeq_Left))

#     if base == TopGenomicSeq_Left and ref_allele in TopGenomicSeq_SNP:
#         return (
#             TopGenomicSeq_SNP[0]
#             if TopGenomicSeq_SNP[1] == ref_allele
#             else TopGenomicSeq_SNP[1]
#         )
#     elif base == SourceSeq_Left and ref_allele in SourceSeq_SNP:
#         return SourceSeq_SNP[0] if SourceSeq_SNP[1] == ref_allele else SourceSeq_SNP[1]
#     else:
#         return "DATA_ERROR"


def get_alt_from_normalized(row):
    complementarity = {"A": "T", "T": "A", "C": "G", "G": "C"}
    if pd.isnull(row["REF"]) or pd.isnull(row["SNP"]) or pd.isnull(row["RefStrand"]):
        return "DATA_ERROR"

    ref_allele = row["REF"]
    snp = row["SNP"].strip("[]").split("/")
    ref_strand = row["RefStrand"]

    if ref_strand == "+":
        if ref_allele in snp:
            return snp[0] if snp[1] == ref_allele else snp[1]
        else:
            return "DATA_ERROR"
    elif ref_strand == "-":
        # complement_ref = complementarity.get(ref_allele)
        snp = [complementarity[snp[0]], complementarity[snp[1]]]
        if ref_allele in snp:
            return snp[0] if snp[1] == ref_allele else snp[1]
            # ALT для - цепи
            # alt_on_minus_strand = snp[0] if snp[1] == complement_ref else snp[1]
            # # ALT Для + цепи
            # return complementarity.get(alt_on_minus_strand)
        else:
            return "DATA_ERROR"
    else:
        return "DATA_ERROR"


rdf["ALT"] = rdf.apply(get_alt_from_normalized, axis=1)


rdf

,SNP Name,Sample ID,Allele1 - AB,Allele2 - AB,Chr_x,Position,IlmnStrand,SNP,MapInfo,Chr_y,SourceSeq_SNP,SourceSeq,TopGenomicSeq_SNP,TopGenomicSeq,SourceStrand,RefStrand,REF,ALT
0,ARS-BFGL-NGS-104320,HORUS007200114646,A,B,0,0,TOP,[A/G],11696849,3,[T/C],TGGCGTGCTGCAATTCATGGGGTCGCAAAGAGTCAGACACGACTGA...,[A/G],TTTATAAATAAATTTATGGATAAACAAAATCAGGTAGGGCCATAAA...,BOT,+,None,DATA_ERROR
1,ARS-BFGL-NGS-55064,HORUS007200114646,A,B,0,0,BOT,[T/C],57139923,22,[A/G],GGGTTCGAGCGCCTCAACCGCAGACCTGCCTGCCTCAACCAAGGCC...,[A/G],GGGTTCGAGCGCCTCAACCGCAGACCTGCCTGCCTCAACCAAGGCC...,TOP,+,None,DATA_ERROR
2,BTA-89233-no-rs,HORUS007200114646,B,B,0,0,BOT,[T/C],31819343,23,[T/C],TATAATACATATAATATTGTTTACAATATTCTGTTGCTTTATTATG...,[A/G],TTAAAATTAATAAAATAAGATCAAGAAAAAATTATCAATATAAGAA...,BOT,-,None,DATA_ERROR
3,ARS-BFGL-NGS-116515,HORUS007200114646,B,A,0,0,TOP,[A/C],4644991,28,[T/G],ATGGGGTCATACAGAGTTGGACACGACTGAAGCGACTTAGCAGCAG...,[A/C],CAACTGAGTGACTGAACTGAAGAATATGTAAATAATTATCGGCCTG...,BOT,-,None,DATA_ERROR
4,UA-IFASA-7534,HORUS007200114646,B,B,0,0,TOP,[A/G],41108931,29,[A/G],GAAGGCTAGCTGACATCAGCCACACAGGAGCTCTTCCTCTCAAGTG...,[A/G],GAAGGCTAGCTGACATCAGCCACACAGGAGCTCTTCCTCTCAAGTG...,TOP,-,None,DATA_ERROR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022222,BovineHD3100001188,HORUS003910309577,-,-,31,7385231,TOP,[A/C],50965063,17,[A/C],GGAGTATAAGTCCATTTCACTTTTCTTTGGGTACTCGTTCCATCAC...,[A/C],GGAGTATAAGTCCATTTCACTTTTCTTTGGGTACTCGTTCCATCAC...,TOP,+,T,DATA_ERROR
1022223,BovineHD3100001052,HORUS003910309577,-,-,31,8919894,TOP,[A/C],0,0,[A/C],AAGGGTTTATTTTTATTGTATGCCAAAAACTACATCCTTTGCAGTG...,[A/C],AAGGGTTTATTTTTATTGTATGCCAAAAACTACATCCTTTGCAGTG...,TOP,+,T,DATA_ERROR
1022224,BovineHD3100001376,HORUS003910309577,-,-,31,9388211,BOT,[T/C],7293970,29,[T/C],AGAAACACATGTGGTGAAGGGGTCTGGAGGTGGGCCCTGTAGTGAC...,[A/G],GGCTCCACAGACAGCTTGCATGTACCTGAGTCATCCCCATTTGGGA...,BOT,-,G,A
1022225,BovineHD3100000364,HORUS003910309577,-,-,31,12978879,BOT,[T/G],0,0,[A/C],AAATCATATAGAAATAGATCTCAGAATTTAAAAAAAAAAAATTGCT...,[A/C],AAATCATATAGAAATAGATCTCAGAATTTAAAAAAAAAAAATTGCT...,TOP,+,T,G
1022226,BovineHD3100001409,HORUS003910309577,-,-,31,42639036,BOT,[T/G],0,0,[A/C],ACAGTGACATATTTGAAGATGTCAGAAGCAATGGGCTAGATTGATT...,[A/C],ACAGTGACATATTTGAAGATGTCAGAAGCAATGGGCTAGATTGATT...,TOP,+,G,T

In [71]:
rdf = rdf[
    [
        "SNP Name",
        "REF",
        "ALT",
        "Chr_y",
        "MapInfo",
        "Chr_x",
        "Position",
        "SNP",
        "SourceSeq_SNP",
        "TopGenomicSeq_SNP",
        "IlmnStrand",
        "SourceStrand",
        "RefStrand",
        "Sample ID",
        "Allele1 - AB",
        "Allele2 - AB",
    ]
]
rdf
# rdf[["SNP Name", "REF", "IlmnStrand", "SNP", "ALT"]].to_csv('2.csv', index=False)

,SNP Name,REF,ALT,Chr_y,MapInfo,Chr_x,Position,SNP,SourceSeq_SNP,TopGenomicSeq_SNP,IlmnStrand,SourceStrand,RefStrand,Sample ID,Allele1 - AB,Allele2 - AB
0,ARS-BFGL-NGS-104320,None,DATA_ERROR,3,11696849,0,0,[A/G],[T/C],[A/G],TOP,BOT,+,HORUS007200114646,A,B
1,ARS-BFGL-NGS-55064,None,DATA_ERROR,22,57139923,0,0,[T/C],[A/G],[A/G],BOT,TOP,+,HORUS007200114646,A,B
2,BTA-89233-no-rs,None,DATA_ERROR,23,31819343,0,0,[T/C],[T/C],[A/G],BOT,BOT,-,HORUS007200114646,B,B
3,ARS-BFGL-NGS-116515,None,DATA_ERROR,28,4644991,0,0,[A/C],[T/G],[A/C],TOP,BOT,-,HORUS007200114646,B,A
4,UA-IFASA-7534,None,DATA_ERROR,29,41108931,0,0,[A/G],[A/G],[A/G],TOP,TOP,-,HORUS007200114646,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022222,BovineHD3100001188,T,DATA_ERROR,17,50965063,31,7385231,[A/C],[A/C],[A/C],TOP,TOP,+,HORUS003910309577,-,-
1022223,BovineHD3100001052,T,DATA_ERROR,0,0,31,8919894,[A/C],[A/C],[A/C],TOP,TOP,+,HORUS003910309577,-,-
1022224,BovineHD3100001376,G,A,29,7293970,31,9388211,[T/C],[T/C],[A/G],BOT,BOT,-,HORUS003910309577,-,-
1022225,BovineHD3100000364,T,G,0,0,31,12978879,[T/G],[A/C],[A/C],BOT,TOP,+,HORUS003910309577,-,-
1022226,BovineHD3100001409,G,T,0,0,31,42639036,[T/G],[A/C],[A/C],BOT,TOP,+,HORUS003910309577,-,-

In [72]:
rdf[rdf["SNP"] == "[A/C]"]

,SNP Name,REF,ALT,Chr_y,MapInfo,Chr_x,Position,SNP,SourceSeq_SNP,TopGenomicSeq_SNP,IlmnStrand,SourceStrand,RefStrand,Sample ID,Allele1 - AB,Allele2 - AB
3,ARS-BFGL-NGS-116515,None,DATA_ERROR,28,4644991,0,0,[A/C],[T/G],[A/C],TOP,BOT,-,HORUS007200114646,B,A
16,ARS-BFGL-NGS-115828,None,DATA_ERROR,6,101565330,0,0,[A/C],[T/G],[A/C],TOP,BOT,-,HORUS007200114646,B,B
30,BTA-110108-no-rs,None,DATA_ERROR,5,33611572,0,0,[A/C],[A/C],[A/C],TOP,TOP,+,HORUS007200114646,B,A
51,BTB-01876530,None,DATA_ERROR,12,910758,0,0,[A/C],[T/G],[A/C],TOP,BOT,-,HORUS007200114646,A,B
58,Hapmap39311-BTA-120041,None,DATA_ERROR,5,79516307,0,0,[A/C],[A/C],[A/C],TOP,TOP,-,HORUS007200114646,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022198,BovineHD3000040012,T,DATA_ERROR,0,0,30,138618767,[A/C],[T/G],[A/C],TOP,BOT,+,HORUS003910309577,B,B
1022218,BovineHD3000041741,T,G,X,144871345,31,4036505,[A/C],[T/G],[A/C],TOP,BOT,-,HORUS003910309577,B,B
1022219,BovineHD3100000519,G,T,22,39921968,31,5340147,[A/C],[A/C],[A/C],TOP,TOP,-,HORUS003910309577,-,-
1022222,BovineHD3100001188,T,DATA_ERROR,17,50965063,31,7385231,[A/C],[A/C],[A/C],TOP,TOP,+,HORUS003910309577,-,-
1022223,BovineHD3100001052,T,DATA_ERROR,0,0,31,8919894,[A/C],[A/C],[A/C],TOP,TOP,+,HORUS003910309577,-,-

In [73]:
rdf["Chr_x"].unique()
rdf["Chr_y"].unique()

array(['3', '22', '23', '28', '29', '14', '15', '8', '6', '1', '2', '19',
       '7', '5', '18', '26', '4', '12', 'X', '13', '9', '24', '21', '10',
       '0', '20', '16', '25', '11', '17', '27'], dtype=object)

In [74]:
total_records = len(rdf)

error_count = len(rdf[rdf["ALT"] == "DATA_ERROR"])

print("Всего записей:", total_records)
print("Всего ошибки:", error_count)

if total_records > 0:
    error_percentage = (error_count / total_records) * 100
    print(f"Процент ошибок: {error_percentage:.2f}%")


display(rdf)

Всего записей: 1022227
Всего ошибки: 25602
Процент ошибок: 2.50%

,SNP Name,REF,ALT,Chr_y,MapInfo,Chr_x,Position,SNP,SourceSeq_SNP,TopGenomicSeq_SNP,IlmnStrand,SourceStrand,RefStrand,Sample ID,Allele1 - AB,Allele2 - AB
0,ARS-BFGL-NGS-104320,None,DATA_ERROR,3,11696849,0,0,[A/G],[T/C],[A/G],TOP,BOT,+,HORUS007200114646,A,B
1,ARS-BFGL-NGS-55064,None,DATA_ERROR,22,57139923,0,0,[T/C],[A/G],[A/G],BOT,TOP,+,HORUS007200114646,A,B
2,BTA-89233-no-rs,None,DATA_ERROR,23,31819343,0,0,[T/C],[T/C],[A/G],BOT,BOT,-,HORUS007200114646,B,B
3,ARS-BFGL-NGS-116515,None,DATA_ERROR,28,4644991,0,0,[A/C],[T/G],[A/C],TOP,BOT,-,HORUS007200114646,B,A
4,UA-IFASA-7534,None,DATA_ERROR,29,41108931,0,0,[A/G],[A/G],[A/G],TOP,TOP,-,HORUS007200114646,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022222,BovineHD3100001188,T,DATA_ERROR,17,50965063,31,7385231,[A/C],[A/C],[A/C],TOP,TOP,+,HORUS003910309577,-,-
1022223,BovineHD3100001052,T,DATA_ERROR,0,0,31,8919894,[A/C],[A/C],[A/C],TOP,TOP,+,HORUS003910309577,-,-
1022224,BovineHD3100001376,G,A,29,7293970,31,9388211,[T/C],[T/C],[A/G],BOT,BOT,-,HORUS003910309577,-,-
1022225,BovineHD3100000364,T,G,0,0,31,12978879,[T/G],[A/C],[A/C],BOT,TOP,+,HORUS003910309577,-,-
1022226,BovineHD3100001409,G,T,0,0,31,42639036,[T/G],[A/C],[A/C],BOT,TOP,+,HORUS003910309577,-,-

In [75]:
rdf = rdf[rdf["ALT"] != "DATA_ERROR"]
rdf = rdf[
    [
        "SNP Name",
        "REF",
        "ALT",
        # "Chr_y",
        # "MapInfo",
        "Chr_x",
        "Position",
        "Sample ID",
        "SNP",
        "SourceSeq_SNP",
        "TopGenomicSeq_SNP",
        "IlmnStrand",
        "SourceStrand",
        "RefStrand",
        "Allele1 - AB",
        "Allele2 - AB",
    ]
]

rdf.to_csv("data_result/thintergen_share_geno_VM2_1_FinalReport.csv", index=False)


display(rdf)

,SNP Name,REF,ALT,Chr_x,Position,Sample ID,SNP,SourceSeq_SNP,TopGenomicSeq_SNP,IlmnStrand,SourceStrand,RefStrand,Allele1 - AB,Allele2 - AB
154,BovineHD0100000005,A,C,1,655346,HORUS007200114646,[A/C],[A/C],[A/C],TOP,TOP,+,B,A
155,Hapmap43437-BTA-101873,A,G,1,776231,HORUS007200114646,[T/C],[A/G],[A/G],BOT,TOP,-,B,A
157,ARS-BFGL-NGS-16466,C,T,1,907810,HORUS007200114646,[A/G],[T/C],[A/G],TOP,BOT,-,B,B
158,BovineHD0100000079,A,G,1,918822,HORUS007200114646,[A/G],[A/G],[A/G],TOP,TOP,+,A,A
159,BovineHD0100000082,G,A,1,930560,HORUS007200114646,[A/G],[A/G],[A/G],TOP,TOP,+,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022220,BovineHD0800019233,T,C,31,6758621,HORUS003910309577,[T/C],[T/C],[A/G],BOT,BOT,+,A,A
1022221,BovineHD3100001414,C,T,31,7084156,HORUS003910309577,[T/C],[T/C],[A/G],BOT,BOT,+,-,-
1022224,BovineHD3100001376,G,A,31,9388211,HORUS003910309577,[T/C],[T/C],[A/G],BOT,BOT,-,-,-
1022225,BovineHD3100000364,T,G,31,12978879,HORUS003910309577,[T/G],[A/C],[A/C],BOT,TOP,+,-,-
1022226,BovineHD3100001409,G,T,31,42639036,HORUS003910309577,[T/G],[A/C],[A/C],BOT,TOP,+,-,-

In [76]:
names_from_df1 = set(snp_map_df["Name"])
names_from_df2 = set(bovinehd_manifest_df["Name"])

common_names = names_from_df1.intersection(names_from_df2)

match_count = len(common_names)

print(f"Количество совпадений(SNP Name в манифесте): {match_count}")
print(f"Количество всего (SNP Name): {len(snp_map_df)}")

Количество совпадений(SNP Name в манифесте): 60131
Количество всего (SNP Name): 63836

In [77]:
df["Allele1 - AB"].unique()

array(['A', 'B', '-'], dtype=object)

In [78]:
len(df["Sample ID"].unique())

17

In [79]:
len(df["SNP Name"].unique())

63836

In [80]:
len(df["Sample ID"].unique()) * len(df["SNP Name"].unique()) == len(df)

True