In [79]:
import random

random.choice(["A", "B"])

sample_id = [f"SAMPLE{i}" for i in range(0, 17)]
len(sample_id)

17

In [80]:
import pandas as pd

input_file = 'test_data_FinalReport.txt'
with open(input_file, 'r') as f:
    skipped_lines = [next(f) for _ in range(9)]  # читаем 9 строк


fr = pd.read_csv("test_data_FinalReport.txt", sep="\t", skiprows=9)

fr

,SNP Name,Sample ID,Allele1 - AB,Allele2 - AB,Chr,Position
0,BovineHD2400000076,HORUS003912556966,-,-,24,112601
1,BovineHD2400000069,HORUS003912556966,B,B,24,163270
2,Hapmap54014-rs29018901,HORUS003912556966,A,B,24,300821
3,BovineHD4100016339,HORUS003912556966,A,B,24,335857
4,ARS-BFGL-NGS-103469,HORUS003912556966,B,B,24,391651
...,...,...,...,...,...,...
1532,BovineHD2400018199,HORUS003912556966,B,A,24,61954180
1533,BTB-01890193,HORUS003912556966,A,A,24,61991351
1534,BovineHD2400018253,HORUS003912556966,A,B,24,62039634
1535,ARS-BFGL-NGS-29191,HORUS003912556966,A,B,24,62127707
1536,BovineHD0700020755,HORUS003912556966,B,A,24,62179612

In [81]:
fr["Sample ID"].unique()

array(['HORUS003912556966'], dtype=object)

In [82]:
sm = pd.read_csv("test_data_SampleMap.txt", sep="\t")

sm

,Index,Name,ID,Gender,Plate,Well,Group,Parent1,Parent2,Replicate,SentrixPosition
0,NaN,NaN,HORUS007200114646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,HORUS006600003564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,HORUS006600003558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,HORUS006600003554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,HORUS006600003552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,HORUS006600003550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,HORUS006600003544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,HORUS006600003520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,HORUS006600003502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,HORUS006600003494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,HORUS006600003490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,HORUS006600003486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,HORUS006600003476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,HORUS006600003428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,HORUS006600003392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,HORUS003912556966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,HORUS003910309577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
snp_m = pd.read_csv("test_data_SNPMap.txt", sep="\t")

snp_m

,Index,Name,Chromosome,Position,GenTrain Score,SNP,ILMN_Strand,Customer Strand,NormID,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,BovineHD2400000076,24,112601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,BovineHD2400000069,24,163270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Hapmap54014-rs29018901,24,300821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,BovineHD4100016339,24,335857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,ARS-BFGL-NGS-103469,24,391651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1532,NaN,BovineHD2400018199,24,61954180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1533,NaN,BTB-01890193,24,61991351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1534,NaN,BovineHD2400018253,24,62039634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1535,NaN,ARS-BFGL-NGS-29191,24,62127707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1536,NaN,BovineHD0700020755,24,62179612,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
se = pd.Series(sample_id, index=sm["ID"])

se

ID
HORUS007200114646     SAMPLE0
HORUS006600003564     SAMPLE1
HORUS006600003558     SAMPLE2
HORUS006600003554     SAMPLE3
HORUS006600003552     SAMPLE4
HORUS006600003550     SAMPLE5
HORUS006600003544     SAMPLE6
HORUS006600003520     SAMPLE7
HORUS006600003502     SAMPLE8
HORUS006600003494     SAMPLE9
HORUS006600003490    SAMPLE10
HORUS006600003486    SAMPLE11
HORUS006600003476    SAMPLE12
HORUS006600003428    SAMPLE13
HORUS006600003392    SAMPLE14
HORUS003912556966    SAMPLE15
HORUS003910309577    SAMPLE16
dtype: object

In [85]:
sm["ID"] = sm["ID"].map(se)

sm

,Index,Name,ID,Gender,Plate,Well,Group,Parent1,Parent2,Replicate,SentrixPosition
0,NaN,NaN,SAMPLE0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,SAMPLE1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,SAMPLE2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,SAMPLE3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,SAMPLE4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,SAMPLE5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,SAMPLE6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,SAMPLE7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,SAMPLE8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,SAMPLE9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,SAMPLE10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,SAMPLE11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,SAMPLE12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,SAMPLE13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,SAMPLE14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,SAMPLE15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,SAMPLE16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
# fr["Sample ID"] = fr["Sample ID"].map(se)

expanded_dfs = []
for i in sample_id:
    tmp_fr = fr.copy()
    tmp_fr["Sample ID"] = i
    expanded_dfs.append(tmp_fr)

result_fr = pd.concat(expanded_dfs, ignore_index=True)



result_fr

,SNP Name,Sample ID,Allele1 - AB,Allele2 - AB,Chr,Position
0,BovineHD2400000076,SAMPLE0,-,-,24,112601
1,BovineHD2400000069,SAMPLE0,B,B,24,163270
2,Hapmap54014-rs29018901,SAMPLE0,A,B,24,300821
3,BovineHD4100016339,SAMPLE0,A,B,24,335857
4,ARS-BFGL-NGS-103469,SAMPLE0,B,B,24,391651
...,...,...,...,...,...,...
26124,BovineHD2400018199,SAMPLE16,B,A,24,61954180
26125,BTB-01890193,SAMPLE16,A,A,24,61991351
26126,BovineHD2400018253,SAMPLE16,A,B,24,62039634
26127,ARS-BFGL-NGS-29191,SAMPLE16,A,B,24,62127707
26128,BovineHD0700020755,SAMPLE16,B,A,24,62179612

In [87]:
result_fr["Allele1 - AB"] = result_fr.apply(lambda _: random.choice(["A", "B"]), axis=1)
result_fr["Allele2 - AB"] = result_fr.apply(lambda _: random.choice(["A", "B"]), axis=1)

In [88]:
result_fr["Sample ID"].unique()

array(['SAMPLE0', 'SAMPLE1', 'SAMPLE2', 'SAMPLE3', 'SAMPLE4', 'SAMPLE5',
       'SAMPLE6', 'SAMPLE7', 'SAMPLE8', 'SAMPLE9', 'SAMPLE10', 'SAMPLE11',
       'SAMPLE12', 'SAMPLE13', 'SAMPLE14', 'SAMPLE15', 'SAMPLE16'],
      dtype=object)

In [89]:
result_fr

,SNP Name,Sample ID,Allele1 - AB,Allele2 - AB,Chr,Position
0,BovineHD2400000076,SAMPLE0,A,A,24,112601
1,BovineHD2400000069,SAMPLE0,A,A,24,163270
2,Hapmap54014-rs29018901,SAMPLE0,A,A,24,300821
3,BovineHD4100016339,SAMPLE0,A,B,24,335857
4,ARS-BFGL-NGS-103469,SAMPLE0,A,A,24,391651
...,...,...,...,...,...,...
26124,BovineHD2400018199,SAMPLE16,A,B,24,61954180
26125,BTB-01890193,SAMPLE16,A,B,24,61991351
26126,BovineHD2400018253,SAMPLE16,B,B,24,62039634
26127,ARS-BFGL-NGS-29191,SAMPLE16,B,B,24,62127707
26128,BovineHD0700020755,SAMPLE16,A,B,24,62179612

In [90]:
skipped_lines

for index, value in enumerate(skipped_lines):
    if value.find("Num SNPs") != -1:
        num_snp_str = value.split("\t")
        num_snp_str[1] = len(snp_m)
        skipped_lines[index] = f"{num_snp_str[0]}\t{num_snp_str[1]}\n"
    if value.find("Total SNPs") != -1:
        num__total_snp_str = value.split("\t")
        num__total_snp_str[1] = len(snp_m)
        skipped_lines[index] = f"{num__total_snp_str[0]}\t{num__total_snp_str[1]}\n"
    if value.find("Num Samples") != -1:
        num_sample_str = value.split("\t")
        num_sample_str[1] = len(sample_id)
        skipped_lines[index] = f"{num_sample_str[0]}\t{num_sample_str[1]}\n"
    if value.find("Total Samples") != -1:
        num_sample_total_str = value.split("\t")
        num_sample_total_str[1] = len(sample_id)
        skipped_lines[index] = f"{num_sample_total_str[0]}\t{num_sample_total_str[1]}\n"
# ['[Header]\n',
#  'GSGT Version\t1.9.4\n',
#  'Processing Date\t05/09/2024 08:16 AM\n',
#  'Content\tAxiom_VM2.r1\n',
#  'Num SNPs\t63836\n',
#  'Total SNPs\t63836\n',
#  'Num Samples\t17\n',
#  'Total Samples\t17\n',
#  '[Data]\n']

In [91]:
output_file = 'test_data_res_FinalReport.txt'
with open(output_file, 'w') as f:
    f.writelines(skipped_lines)               # записываем комментарии
    result_fr.to_csv(f, index=False, sep="\t")                  # добавляем данные

In [92]:
sm.to_csv("test_data_res_SampleMap.txt", index=False, sep="\t")

In [93]:
snp_m.columns = ['' if col.startswith('Unnamed') else col for col in snp_m.columns]

snp_m.to_csv("test_data_res_SNPMap.txt", index=False, sep="\t")

In [94]:
%%bash
zip -9 /scratch/storageA/zaleski_bulls/bulls-vcf-pipeline/tests/data/raw/test_data.zip test_data_res_FinalReport.txt test_data_res_SampleMap.txt test_data_res_SNPMap.txt

updating: test_data_res_FinalReport.txt (deflated 77%)
updating: test_data_res_SampleMap.txt (deflated 67%)
updating: test_data_res_SNPMap.txt (deflated 76%)